version: 0.0
os: linux

#- source: app/docker-compose.yml

#files:
 # - source: /
  #  destination: /home/ec2-user/app

files:
  # Copy everything from repo to /home/ec2-user/app
  - source: /
    destination: /home/ec2-user/app

permissions:
  - object: /home/ec2-user/app
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
  - object: /home/ec2-user/app/docker-compose.yml
    owner: ec2-user
    group: ec2-user
    mode: 644
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/verify.sh
      timeout: 60
      runas: ec2-user
